apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: eduazureregistrylsk.azurecr.io/backend-java # 이미지 주소 변경필요
    newTag: -20240809052052

commonLabels:
  app: backend-java
  environment: dev
